/**
 * Application Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The default keywords and authors are injected during the CI/CD build process
 * from the DEFAULT_KEYWORDS and DEFAULT_AUTHORS variables configured in GitHub repository settings
 */

const APP_CONFIG = {
    /**
     * Default keywords for filtering papers
     * This will be replaced during GitHub Actions workflow execution
     */
    defaultKeywords: '',

    /**
     * Default authors for filtering papers
     * This will be replaced during GitHub Actions workflow execution
     */
    defaultAuthors: ''
};